name: Convert Butane to Ignition and Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  convert-and-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install latest Butane CLI
      - name: Install Butane
        run: |
          # Fetch the latest release version from GitHub API
          LATEST_VERSION=$(curl -s https://api.github.com/repos/coreos/butane/releases/latest | grep tag_name | cut -d '"' -f 4)
          curl -sSL https://github.com/coreos/butane/releases/download/${LATEST_VERSION}/butane-x86_64-unknown-linux-gnu -o butane
          chmod +x butane
          sudo mv butane /usr/local/bin/

      # Convert Butane files to Ignition
      - name: Convert Butane to Ignition
        run: |
          mkdir -p ignition-files
          for file in $(find . -type f \( -name "*.bu" -o -name "*.butane" \)); do
            output_file="ignition-files/$(basename "${file%.*}").ign"
            butane --pretty --strict "$file" -o "$output_file"
          done

      # Create a release and upload Ignition files
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: commit-${{ github.sha }}
          release_name: Commit ${{ github.sha }}
          draft: false
          prerelease: true

      # Upload each Ignition file as a release asset
      - name: Upload Ignition Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in ignition-files/*.ign; do
            gh release upload commit-${{ github.sha }} "$file" --repo ${{ github.repository }}
          done